name: This is second workflow
on: [workflow_dispatch]
  #- push
   
jobs:
 firstJob:
   needs: my_third_job
   runs-on: ubuntu-latest
   env:
      hostname: DevOps
      app: githubaction
   steps:
      - name: Checking the hostname
        run: |
          sudo hostname
      - name: Set New hostname
        run: |
          sudo hostnamectl set-hostname "$hostname"
          hostname
      - name: Checking the Condition using Env
        if: ${{ env.app == 'githubaction' }}
        run: echo "True"

#  my_second_job:
#             needs: my_fourth_job
#             runs-on: ubuntu-latest
#             steps:
#               - name: Checkout code
#                 uses: actions/checkout@v3            
              
#               - name: Cache node modules
#                 id: cache-npm
#                 uses: actions/cache@v3
#                 with: 
#                  path: ~/.npm
#                  key: cachemodule-${{ hashFiles('**/package.-lock.json') }}  
          
               
#               - name: Setup Node.js
#                 uses: actions/setup-node@v2
#                 with: 
#                       node-version: 14
#               - name: Install Dependencies
#                 run: npm install 

#               # - name: Installing react
#               #   run: npm i react-scripts
              
#               - name: Build the app
#                 run: npm run build

#               - name: NPM start
#                 run: npm start
#               - run: echo "Build Successful"
#               - name: Upload artifact 
#                 uses: actions/upload-artifact@v3
#                 with:
#                     name: final-build
#                     path: |
#                         artifacts/
#                         package.json  
#                         path/output/bin/
#                     retention-days: 90
    
 my_third_job:
            runs-on: ubuntu-latest
            steps: 
            - name: Job 3
              run: echo "Third job Execution ."
 my_fourth_job: 
            needs: firstJob
            runs-on: ubuntu-latest
            steps: 
             - name: Checkout code
               uses: actions/checkout@v3            
              

          ## --------- Cache Module ----------
            #  - name: Cache node modules
            #    id: cache-npm
            #    uses: actions/cache@v3
            #    with: 
            #         path: ~/.npm
            #         key: cachemodule-${{ hashFiles('**/package.-lock.json') }}
         

          ## -------- Setup NPM --------------
             - uses: actions/setup-node@v3
               with:
                   node-version: 14
                   cache: 'npm'
             
             - run: npm ci      
             - run: npm run build

             - name: NPM start
               run: npm start
             
              #- name: Setup Node.js
           #     uses: actions/setup-node@v2
            #  with: 
            #            node-version: 14
            #  - name: Install Dependencies
            #    run: npm install 

            # #  - name: Install React
            # #    run: npm i react-scripts
                  
            #  - name: Build the app
            #    run: npm run build
       
    
             - run: echo "Build Successful"

          ## ------- Downloading the Artifacts ---------
#  myjob-5: 
#           name: Downloading build artifact
#           needs: my_second_job
#           runs-on:  ubuntu-latest 
#           steps: 
#              - name: Download Artifact
#                uses: actions/download-artifact@v3
#                with:
#                  name: final-build
#              - name: Test the artifact
#                run: ls -R 
